---
- name: Create an issue
  jira:
    uri: "{{ jira_uri }}"
    username: "{{ jira_username }}"
    password: "{{ jira_password }}"
    project: OPS
    operation: create
    summary: "Testing Ansible Tower to JIRA {{ ansible_date_time.iso8601 }}"
    description: "Created using Ansible"
    issuetype: Ops-Task
  register: issue
...