---
- name: backup device configs
  cisco.ios.ios_config:
    src: /var/tmp/configs/{{ ansible_network_os }}/ios_template.j2
    backup: yes
    backup_options:
      filename: {{ ansible_hostname }}.cfg
      dir_path: /var/tmp/backups/{{ ansible_network_os }}/
...