---
- name: create git repo
  git:
    repo: https://{{ gitusername | urlencode }}:{{ gitpassword }}@dev.azure.com/itsals/Network%20Engineering/_git/Tower
    dest: /var/tmp/tower-config-repo
    update: yes
    version: master

- name: create {{ device_os }} configration file
  template:
    src: templates/{{ device_os }}.j2
    dest: /var/tmp/tower-config-repo/configs/{{ sidecode }}-{{ device_os }}-{{ ansible_date_time.date }}-{{ ansible_date_time.time }}.conf

- name: add template to git
  command: "git add --all"
  args:
    chdir: /var/tmp/tower-config-repo/
  register: gitadd

- name: commit to git
  command: git commit -a -m "added config for {{ device_os }}-{{ ansible_date_time.date }}-{{ ansible_date_time.time }}"
  args:
    chdir: /var/tmp/tower-config-repo/
  register: gitcommit

- name: push to git
  command: git push
  args:
    chdir: /var/tmp/tower-config-repo/
  register: gitpush