---
- name: Ensure that the /var/tmp/tower-config-repo directory is present
  file:
      path: /var/tmp/tower-config-repo/configs
      state: directory

- name: generate {{ ansible_network_os }} config file
  template:
    src: templates/{{ ansible_network_os }}.j2
    dest: /var/tmp/configs/{{ ansible_network_os }}/ios_template.j2
...