---
- debug:
    msg: "START linux.yml"

#
# Execute setup module.
#
- name: Execute show commands to collect device info
  setup:
    filter: ansible_distribution_version
  register: linux_facts

#
# Set common facts
#
- name: set version fact
  set_fact:
    version: "{{ (linux_facts)['ansible_facts']['ansible_distribution_version'] }}"

